=== HICgroup/ShineTpcCalibration/Stage2/Modules/DriftVelocityFromTOFPK/DriftVelocityFromTOFPK.xsd
<xsd:schema
  xmlns:xsd='http://www.w3.org/2001/XMLSchema'
  xmlns:shine="http://cern.ch/na61/schema/types">

  <xsd:import
    namespace="http://cern.ch/na61/schema/types"
    schemaLocation="[SCHEMAPATH_IMPORTS]/ShineSchemaTypes.xsd"/>

  <xsd:element name="DriftVelocityFromTOFPK">
     <xsd:complexType>
       <xsd:sequence>
         <xsd:element name="nMinVTPC1Clusters" type="xsd:unsignedInt"/>
         <xsd:element name="nMinVTPC2Clusters" type="xsd:unsignedInt"/>
         <xsd:element name="nMinMTPCLClusters" type="xsd:unsignedInt"/>
         <xsd:element name="nMinMTPCRClusters" type="xsd:unsignedInt"/>
         <xsd:element name="nMinGTPCClusters" type="xsd:unsignedInt"/>
         <xsd:element name="localXLeftMarginGTPCBeamSpot" type="shine:doubleWithUnit"/>
         <xsd:element name="localXRightMarginGTPCBeamSpot" type="shine:doubleWithUnit"/>
         <xsd:element name="timeOfFlightMin" type="shine:doubleWithUnit"/>
         <xsd:element name="timeOfFlightMax" type="shine:doubleWithUnit"/>
         <xsd:element name="normalizedChargeMin" type="xsd:double"/>
         <xsd:element name="normalizedChargeMax" type="xsd:double"/>
         <xsd:element name="trackMatchOutputFileName" type="xsd:string"/>
       </xsd:sequence>
     </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== HICgroup/ShineTpcCalibration/Stage2/Modules/DriftVelocityFromTOFPK/DriftVelocityFromTOFPK.xml
<?xml version="1.0" encoding="iso-8859-1"?>

<!-- Configuration of Module DriftVelocityFromTOFPK -->

<DriftVelocityFromTOFPK
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation='[SCHEMAPATH]/DriftVelocityFromTOFPK.xsd'>

  <!-- number of clusters cut on local tracks -->
  <nMinVTPC1Clusters> 20 </nMinVTPC1Clusters>
  <nMinVTPC2Clusters> 20 </nMinVTPC2Clusters>
  <nMinMTPCLClusters> 40 </nMinMTPCLClusters>
  <nMinMTPCRClusters> 40 </nMinMTPCRClusters>
  <nMinGTPCClusters>  5  </nMinGTPCClusters>
  <!-- GTPC beam spot cut in X strip to reject off-times -->
  <localXLeftMarginGTPCBeamSpot unit="cm"> -2.0 </localXLeftMarginGTPCBeamSpot>
  <localXRightMarginGTPCBeamSpot unit="cm"> 7.0 </localXRightMarginGTPCBeamSpot>
  <!-- ToF hit validity cut -->
  <timeOfFlightMin unit="nanosecond"> 44.0 </timeOfFlightMin>
  <timeOfFlightMax unit="nanosecond"> 53.0 </timeOfFlightMax>
  <normalizedChargeMin> 0.7 </normalizedChargeMin>
  <normalizedChargeMax> 1.7 </normalizedChargeMax>

  <!-- file name of output root file with track matching differences -->
  <trackMatchOutputFileName> trackMatchDump.root </trackMatchOutputFileName>

</DriftVelocityFromTOFPK>
